name: Scheduled Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8 点运行 (UTC 0:00)
  workflow_dispatch:   # 允许手动点击按钮触发同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: vikiboss/60s  # <-- 修改这里，例如: google/googletest
          upstream_branch: main                # <-- 修改这里，上游的主分支名
          target_branch: main                  # <-- 修改这里，你的主分支名
          test_mode: false
