name: Scheduled Sync Upstream

on:
  schedule:
    - cron: '0 21 * * *' # 北京时间凌晨 5 点 (UTC 21:00)
  workflow_dispatch:   # 允许你随时手动点击按钮测试

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          # 注意：以下三个参数名已经更新，请务必保持一致
          upstream_sync_repo: vikiboss/60s
          upstream_sync_branch: main
          target_sync_branch: main
          test_mode: false
